import { API_BASE_URL } from '../config/apiConfig';

export const api = {
    login: `${API_BASE_URL}/api/v1/user/login`,
    register: `${API_BASE_URL}/api/v1/user/insertOne`,
    update: `${API_BASE_URL}/api/v1/user/updateById`,
    findByUserName: `${API_BASE_URL}/api/v1/user/findByUserName`,
    Question: `${API_BASE_URL}/api/v1/question/create`,
    categoryIdByName: `${API_BASE_URL}/api/v1/game-categories/id-by-name`,
    latestGameByCategory: `${API_BASE_URL}/api/v1/game/by-category`,
    gameQuestionsByGame: `${API_BASE_URL}/api/v1/game-questions/by-game`,
    audioByQuestion: `${API_BASE_URL}/api/v1/audio/by-question`,
    storyNameList: `${API_BASE_URL}/api/v1/story-name/list`,
    storyCover: `${API_BASE_URL}/api/v1/story-name/stream`,
    storySearch: `${API_BASE_URL}/api/v1/story-name/search`,
    storyDetails: `${API_BASE_URL}/api/v1/story`,
    storyAudioByStoryName: `${API_BASE_URL}/api/v1/story-audio/by-story-name`,
    storyAudioStream: `${API_BASE_URL}/api/v1/story-audio/stream`,
    storyCollectionList: `${API_BASE_URL}/api/v1/story-collection`,
    storyCollectionAdd: `${API_BASE_URL}/api/v1/story-collection/add`,
    storyCollectionRemove: `${API_BASE_URL}/api/v1/story-collection/remove`,
    vocabCategoriesList: `${API_BASE_URL}/api/v1/vocab-categories/list`,
    vocabCategoryImage: `${API_BASE_URL}/api/v1/vocab-categories/stream`,
    vocabCardsByCategory: `${API_BASE_URL}/api/v1/vocab-cards/by-category`,
    vocabAudioStream: `${API_BASE_URL}/api/v1/vocab-audio/stream`,
    sentenceByCard: `${API_BASE_URL}/api/v1/sentences/by-card`,
    sentenceAudioStream: `${API_BASE_URL}/api/v1/sentence-audio/stream`,
    vocabCollectionList: `${API_BASE_URL}/api/v1/vocab-collection`,
    vocabCollectionToggle: `${API_BASE_URL}/api/v1/vocab-collection/toggle`,
    vocabCardById: `${API_BASE_URL}/api/v1/vocab-cards`,
    chatChooseList: `${API_BASE_URL}/api/v1/chat-choose/list`,
    chatChooseById: `${API_BASE_URL}/api/v1/chat-choose`,
    scenarioStart: `${API_BASE_URL}/api/v1/scenario/start`,
    scenarioTurnText: `${API_BASE_URL}/api/v1/scenario/turn_text`,
    scenarioVoiceTurn: `${API_BASE_URL}/api/v1/scenario/voice_turn`,
    vocabProgress: `${API_BASE_URL}/api/v1/vocab-progress`,
    vocabProgressUpdate: `${API_BASE_URL}/api/v1/vocab-progress/update`,
    vocabularyPicturesByCategory: `${API_BASE_URL}/api/v1/vocabulary-pictures/by-category`,
    vocabularyPictureStream: `${API_BASE_URL}/api/v1/vocabulary-pictures/stream`,
    vocabularyPictureByCard: `${API_BASE_URL}/api/v1/vocabulary-pictures/by-card`,
    // 地圖相關 API
    mapBoardFindAll: `${API_BASE_URL}/api/v1/map-board/findAll`,
    mapBoardFindById: `${API_BASE_URL}/api/v1/map-board/findById`,
    mapNodeFindByBoardId: `${API_BASE_URL}/api/v1/map-node/findByBoardId`,
    mapNodeFindById: `${API_BASE_URL}/api/v1/map-node/findById`,
    mapEdgeFindByBoardId: `${API_BASE_URL}/api/v1/map-edge/findByBoardId`,
    mapEdgeFindFromNode: `${API_BASE_URL}/api/v1/map-edge/findFromNode`,
    gameMove: `${API_BASE_URL}/api/v1/game/move`,
    gameMapInfo: `${API_BASE_URL}/api/v1/game/mapInfo`,
    // 卡片相關 API
    cardByCode: `${API_BASE_URL}/api/v1/cards`,
    cardUse: `${API_BASE_URL}/api/v1/game/use-card`,
    cardSwapPositions: `${API_BASE_URL}/api/v1/game/swap-positions`,
    roomCreate: `${API_BASE_URL}/api/v1/rooms/create`,
    roomGetByCode: `${API_BASE_URL}/api/v1/rooms`,
    roomJoin: `${API_BASE_URL}/api/v1/rooms`,
    roomLeave: `${API_BASE_URL}/api/v1/rooms`,
    roomUpdateReady: `${API_BASE_URL}/api/v1/rooms`,
    roomUpdateStatus: `${API_BASE_URL}/api/v1/rooms`
} as const;